sudo: required
language: node_js
install: yarn install
script: yarn test
node_js:
  - node
notifications:
  email: false
  slack:
    if: branch = master OR branch = develop
    rooms:
      - mhh2019-nhom19:GaOgrwiRiw9dvRdBFAlCClYp#backend-develop

