language: node_js
install: yarn install
script: yarn test
node_js:
  - node
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app:
    master: mobilesale-be-production
    develop: mobilesale-be-staging
notifications:
  email: false
  slack:
    if: branch = master OR branch = develop
    rooms: $SLACK_ID:$SLACK_TOKEN
