const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;
const NONAUTHORITATIVEINFORMATION = 203;
const NOCONTENT = 204;
const BADREQUEST = 400;
const UNAUTHORIZED = 401;
const PAYMENTREQUIRED = 402;
const FORBIDDEN = 403;
const NOTFOUND = 404;
const METHODNOTALLOWED = 405;
const NOTACCEPTABLE = 406;
const PROXYAUTHENTICATIONREQUIRED = 407;
const REQUESTTIMEOUT = 408;
const CONFLICT = 409;
const GONE = 410;
const LENGTHREQUIRED = 411;
const PRECONDITIONFAILED = 412;
const PAYLOADTOOLARGE = 413;
const URITOOLONG = 414;
const UNSUPPORTEDMEDIATYPE = 415;
const RANGENOTSATISFIABLE = 416;
const EXPECTATIONFAILED = 417;
const IMATEAPOT = 418;
const MISDIRECTEDREQUEST = 421;
const UNPROCESSABLEENTITY = 422;
const LOCKED = 423;
const FAILEDDEPENDENCY = 424;
const UNORDEREDCOLLECTION = 425;
const UPGRADEREQUIRED = 426;
const PRECONDITIONREQUIRED = 428;
const TOOMANYREQUESTS = 429;
const REQUESTHEADERFIELDSTOOLARGE = 431;
const UNAVAILABLEFORLEGALREASONS = 451;
const INTERNALSERVERERROR = 500;
const NOTIMPLEMENTED = 501;
const BADGATEWAY = 502;
const SERVICEUNAVAILABLE = 503;
const GATEWAYTIMEOUT = 504;
const HTTPVERSIONNOTSUPPORTED = 505;
const VARIANTALSONEGOTIATES = 506;
const INSUFFICIENTSTORAGE = 507;
const LOOPDETECTED = 508;
const BANDWIDTHLIMITEXCEEDED = 509;
const NOTEXTENDED = 510;
const NETWORKAUTHENTICATIONREQUIRED = 511;

const httpError = {
  OK,
  CREATED,
  ACCEPTED,
  NONAUTHORITATIVEINFORMATION,
  NOCONTENT,
  BADREQUEST,
  UNAUTHORIZED,
  PAYMENTREQUIRED,
  FORBIDDEN,
  NOTFOUND,
  METHODNOTALLOWED,
  NOTACCEPTABLE,
  PROXYAUTHENTICATIONREQUIRED,
  REQUESTTIMEOUT,
  CONFLICT,
  GONE,
  LENGTHREQUIRED,
  PRECONDITIONFAILED,
  PAYLOADTOOLARGE,
  URITOOLONG,
  UNSUPPORTEDMEDIATYPE,
  RANGENOTSATISFIABLE,
  EXPECTATIONFAILED,
  IMATEAPOT,
  MISDIRECTEDREQUEST,
  UNPROCESSABLEENTITY,
  LOCKED,
  FAILEDDEPENDENCY,
  UNORDEREDCOLLECTION,
  UPGRADEREQUIRED,
  PRECONDITIONREQUIRED,
  TOOMANYREQUESTS,
  REQUESTHEADERFIELDSTOOLARGE,
  UNAVAILABLEFORLEGALREASONS,
  INTERNALSERVERERROR,
  NOTIMPLEMENTED,
  BADGATEWAY,
  SERVICEUNAVAILABLE,
  GATEWAYTIMEOUT,
  HTTPVERSIONNOTSUPPORTED,
  VARIANTALSONEGOTIATES,
  INSUFFICIENTSTORAGE,
  LOOPDETECTED,
  BANDWIDTHLIMITEXCEEDED,
  NOTEXTENDED,
  NETWORKAUTHENTICATIONREQUIRED,
};

export default httpError;
export {
  OK,
  CREATED,
  ACCEPTED,
  NONAUTHORITATIVEINFORMATION,
  NOCONTENT,
  BADREQUEST,
  UNAUTHORIZED,
  PAYMENTREQUIRED,
  FORBIDDEN,
  NOTFOUND,
  METHODNOTALLOWED,
  NOTACCEPTABLE,
  PROXYAUTHENTICATIONREQUIRED,
  REQUESTTIMEOUT,
  CONFLICT,
  GONE,
  LENGTHREQUIRED,
  PRECONDITIONFAILED,
  PAYLOADTOOLARGE,
  URITOOLONG,
  UNSUPPORTEDMEDIATYPE,
  RANGENOTSATISFIABLE,
  EXPECTATIONFAILED,
  IMATEAPOT,
  MISDIRECTEDREQUEST,
  UNPROCESSABLEENTITY,
  LOCKED,
  FAILEDDEPENDENCY,
  UNORDEREDCOLLECTION,
  UPGRADEREQUIRED,
  PRECONDITIONREQUIRED,
  TOOMANYREQUESTS,
  REQUESTHEADERFIELDSTOOLARGE,
  UNAVAILABLEFORLEGALREASONS,
  INTERNALSERVERERROR,
  NOTIMPLEMENTED,
  BADGATEWAY,
  SERVICEUNAVAILABLE,
  GATEWAYTIMEOUT,
  HTTPVERSIONNOTSUPPORTED,
  VARIANTALSONEGOTIATES,
  INSUFFICIENTSTORAGE,
  LOOPDETECTED,
  BANDWIDTHLIMITEXCEEDED,
  NOTEXTENDED,
  NETWORKAUTHENTICATIONREQUIRED,
};
